### ISSUE TITLE
Formato del código

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twE105_1920-getbus#3]
Usad [indentado](https://es.wikipedia.org/wiki/Indentaci%C3%B3n#Sangrado_en_C) en el código para facilitar la lectura del mismo.

**Comment by raulcarrero** [comment]
Por alguna razón github no detecta el indentado ya que en devC++ lo visualizo correctamente

**Comment by oscarperpinan** [comment]
GitHub no aplica formato en los ficheros. Lo que ves en el repositorio es una copia literal de lo que haya en tu copia local una vez sincronizadas. 
En el código hay indentado, pero es no está bien aplicado en toda su extensión. Por ejemplo:
 
https://github.com/aigora/twE105_1920-getbus/blob/25332749528c6fd0f917f94c1dd84729198ae7f0/TRABAJO.c#L25-L27

https://github.com/aigora/twE105_1920-getbus/blob/25332749528c6fd0f917f94c1dd84729198ae7f0/TRABAJO.c#L77-L84
